spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&nullNamePatternMatchersAll=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: cn07019820
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 3
      maximumPoolSize: 13
  jpa:
    open-in-view: false
    generate-ddl: false # Initialize the schema on startup.
    hibernate:
      ddl-auto: update # update if schema is changed
      use-new-in-generate-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true # show sql logs
  liquibase:
    enabled: false # disable liquibase
    drop-first: false # ignores schema
    change-log: classpath:changelog.yaml