server:
  port: 8080

spring:
  application:
    name: customer-handler-service
  config:
    import: >
      application-jackson.yml,
      application-database.yml
  cloud:
    config:
      enabled: false