server:
  port: 8080

spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  cloud:
    config:
      enabled: false
  application:
    name: customer-handler-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&autoReconnect=true&nullNamePatternMatchersAll=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: cn07019820
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 3
      maximumPoolSize: 13
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update # update if schema is changed
      use-new-in-generate-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true # show sql logs
  liquibase:
    enabled: false # disable liquibase. todo run and test
    drop-first: false # don't
    change-log: classpath:changelog.yaml